version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn content_repurposer.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - content-repurposer-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A content_repurposer.workers.celery_app worker --loglevel=info
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - content-repurposer-network

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    networks:
      - content-repurposer-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=content_repurposer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - content-repurposer-network

networks:
  content-repurposer-network:
    driver: bridge

volumes:
  postgres_data:
